### ISSUE TITLE
Consolidate the dashboard jobs to run on one server (rather than n+1 RasPis)

### ISSUE THREAD

**Issue by stephenyeargin** [websages/dashboards-bnagh#18]
Part of the CPU/memory issue is that we're trying to run a full Sinatra app and a browser on a resource constrained platform. We should offload this to one location (say, `watchtower`) and have the Raspberry Pi boxes connect and just run the browser.

**Comment by stephenyeargin** [comment]
@jameswhite Like I told you asshole.

**Comment by jameswhite** [comment]
Dashing has been installed on planck.bna.github.net (10.255.2.244) and all raspis with displays now point to it for chromium kiosk mode.
