### ISSUE TITLE
Puppycams should be a dashboard 

### ISSUE THREAD

**Issue by bval** [websages/dashboards-bnagh#27]
Instead of the custom webpage let's put each cam in a dashing widget in a separate dashing layout.

**Comment by stephenyeargin** [comment]
Who consumes the dashboard, unless it's so we can all narcissisticaly  look at ourselves? :smile: 

The way the RasPis are currently configured at the Bikeshed, they load based on screen resolution definition. So it would need to be a dashboard with a specified resolution in the route name.

**Comment by bval** [comment]
I wasn't thinking of putting the puppycams on the physical dashboards at the bikeshed, just suggesting they be served via dashing rather than another service. Those of us in other locations might like to throw them up on a physical dashboard, perhaps rotating with the other dashboard.

**Comment by jameswhite** [comment]
That resolution thing was just me being lazy, we should probably load them by hostname or something unique to the machine, as we've got 2 dashboards with the exact same resolution 2 feet apart and it's always been kind of redundant.

**Comment by stephenyeargin** [comment]
#29 resolved the first bit about loading by hostname instead of resolution.

Cams are now on https://dashboard.thebikeshed.io/keg-left

**Comment by bval** [comment]
:metal:
