### ISSUE TITLE
Load dashboards by hostname instead of screen resolution

### ISSUE THREAD

**Issue by stephenyeargin** [websages/dashboards-bnagh#29]
Plan is to change the Raspberry Pis to load a dashboard by its assigned hostname instead of a screen resolution. As it turns out, there are n+1 screens that are identical models.

- `door`
- `television`
- `keg-left`
- `keg-right`

cc @jameswhite

**Comment by jameswhite** [comment]
:+1:

**Comment by jameswhite** [comment]
I'll get the hosts renamed and the script modified to use those.

**Comment by jameswhite** [comment]
Actually, let's name the door one embark, as to not confuse it with the one that's literally mounted on the door.

**Comment by stephenyeargin** [comment]
>Actually, let's name the door one embark, as to not confuse it with the one that's literally mounted on the door.

k

**Comment by stephenyeargin** [comment]
![screen shot 2016-03-16 at 8 00 04 pm](https://cloud.githubusercontent.com/assets/80459/13833231/c6b5356a-ebb1-11e5-9d0e-60ad620025cd.png)
